=== hex705/tiles/eclipse/labels/bin/data/tileset.dtd
<!ELEMENT tileset (tile*)>
<!ELEMENT tile (name, connections)>
<!ATTLIST tile topcodeID CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT connections EMPTY>
<!ATTLIST connections L (0|1|2|3|4|5|6) "0">
<!ATTLIST connections R (0|1|2|3|4|5|6) "0">
<!ATTLIST connections T (0|1|2|3|4|5|6) "0">
<!ATTLIST connections B (0|1|2|3|4|5|6) "0">

=== hex705/tiles/eclipse/labels/src/data/tileset.xml
<?xml version="1.0"?>
<!DOCTYPE tileset SYSTEM "tileset.dtd">
<tileset>
	<tile topcodeID="47">
		<name>Serial</name>
		<connections L="1" R="3" />
	</tile>	
	<tile topcodeID="55">
		<name>Internet (Processing)</name>
		<connections L="1" R="5" />
	</tile>	
	<tile topcodeID="61">
		<name>Internet (Shield)</name>
		<connections R="5" T="2" B="2" />
	</tile>	
	<tile topcodeID="79">
		<name>Wifi</name>
		<connections R="5" T="2" B="2" />
	</tile>	
	<tile topcodeID="93">
		<name>Ethernet</name>
		<connections R="5" T="2" B="2" />
	</tile>	
	<tile topcodeID="121">
		<name>Arduino</name>
		<connections R="3" B="2" />
	</tile>	
	<tile topcodeID="167">
		<name>X-Bee Shield</name>
		<connections L="3" R="4" T="2" B="2"/>
	</tile>	
	<tile topcodeID="185">
		<name>X-Bee Explorer</name>
		<connections L="3" R="4" />
	</tile>	
	<tile topcodeID="213">
		<name>X-Bee Breakout</name>
		<connections L="3" R="4" />
	</tile>	
	<tile topcodeID="339">
		<name>Processing</name>
		<connections L="1" R="1" T="1" B="1" />
	</tile>	
</tileset>

=== hex705/tiles/eclipse/labels/bin/data/tileset.xml
<?xml version="1.0"?>
<!DOCTYPE tileset SYSTEM "tileset.dtd">
<tileset>
	<tile topcodeID="47" type="data_transport">
		<name>PRO-Serial</name>
		<connections L="3" R="1" />
	</tile>	
	<tile topcodeID="55" type="data_transport">
		<name>PRO-Internet</name>
		<connections L="1" R="5" />
	</tile>	
	<tile topcodeID="61" type="data_transport">
		<name>ARD-Wifi</name>
		<connections R="5" T="2" />
	</tile>	
	<tile topcodeID="93" type="data_transport">
		<name>ARD-Ethernet</name>
		<connections R="5" T="2" />
	</tile>	
	<tile topcodeID="121" type="hub">
		<name>Arduino</name>
		<connections R="3" B="2" />
	</tile>	
	<tile topcodeID="167" type="data_transport">
		<name>xBee Shield</name>
		<connections L="3" R="4" T="2" />
	</tile>	
	<tile topcodeID="185" type="data_transport">
		<name>xBee X-plorer</name>
		<connections L="4" R="3" />
	</tile>	
	<tile topcodeID="213" type="data_transport">
		<name>xBee Breakout</name>
		<connections L="3" R="4" />
	</tile>	
	<tile topcodeID="339" type="hub">
		<name>Processing</name>
		<connections L="1" R="1" T="1" B="1" />
	</tile>	
	<tile topcodeID="333" type="data_protocol">
		<name>OSC</name>
		<connections L="6" R="3" T="4" B="5" />
	</tile>	
	<tile topcodeID="171" type="hub">
		<name>Android</name>
		<connections L="7" R="7" T="7" B="7" />
	</tile>	
	<tile topcodeID="173" type="data_transport">
		<name>AND-Internet</name>
		<connections L="7" R="5" />
	</tile>	
</tileset>
